### ISSUE TITLE
[Question] How to use during Maven build ?

### ISSUE THREAD

**Issue by hiveship** [hevayo/swagger2cxf-maven-plugin#5]
Can you provide a little explanation about how I can use your plugin during my Maven build ?

**Comment by hevayo** [comment]
Server Stub Generation

First you need to include the API definition inside maven project an ideal place to have it is under “src/main/resources/api.yaml”.

To generate the server stubs we uses swagger-codegen https://github.com/swagger-api/swagger-codegen. 

Add the following plug-in to the project.

``` xml
<plugin>
   <groupId>org.wso2.maven.plugins</groupId>
   <artifactId>swagger2cxf-maven-plugin</artifactId>
   <version>1.0-SNAPSHOT</version>
   <configuration>
       <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
   </configuration>
</plugin>
```

Then use “mvn swagger2cxf:generate” command to generate the server stub. You can re run the same command each time you update the API Definition.

The generated code will be at “src/gen/java” so we need to add this to the build which can be done by maven build helper plugin as below.

``` xml
<plugin>
   <groupId>org.codehaus.mojo</groupId>
   <artifactId>build-helper-maven-plugin</artifactId>
   <version>1.9.1</version>
   <executions>
       <execution>
           <id>add-source</id>
           <phase>generate-sources</phase>
           <goals>
               <goal>add-source</goal>
           </goals>
           <configuration>
               <sources>
                   <source>src/gen/java</source>
               </sources>
           </configuration>
       </execution>
   </executions>
</plugin>
```

**Comment by hiveship** [comment]
Thank you for answer. I tried it, but I got the following error at the beginning of the build (I'm using Eclipse on Windows):

```
[ERROR] No plugin found for prefix 'swagger2cxf' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\mnantel\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
```

**Comment by hiveship** [comment]
Thank you. This issue can be closed.
